version: "3"
services:
  okmtyuta-design:
    container_name: "okmtyuta-design"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${OKMTYUTA_DESIGN_PORT}:${OKMTYUTA_DESIGN_PORT}
    # command: gunicorn --bind '0.0.0.0:8001' --chdir /app config.wsgi
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:14.6
    tty: true
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
